import { supabase } from './supabase';
import type { Product } from '../types';

const UNSPLASH = {
  tikuvchilik: [
    '/photo_2026-06-06_19-24-14.jpg',
    '/photo_2026-06-06_19-24-24.jpg',
  ],
  korpa_toshak: [
    '/photo_2026-06-06_19-21-51.jpg',
    '/photo_2026-06-06_19-23-28.jpg',
  ],
  qogirchoq: [
    '/photo_2026-06-06_19-23-54.jpg',
    '/photo_2026-06-06_19-24-21.jpg',
  ],
  gulchilik: [
    '/photo_2026-06-06_19-24-31.jpg',
    '/photo_2026-06-06_19-24-05.jpg',
  ],
  toqivchilik: [
    '/photo_2026-06-06_19-23-05.jpg',
    '/photo_2026-06-06_19-24-09.jpg',
  ],
  qandolatchilik: [
    '/photo_2026-06-06_19-24-27.jpg',
    '/photo_2026-06-06_19-24-36.jpg',
  ],
};

const seedProducts: Omit<Product, 'id' | 'created_at'>[] = [
  {
    title_uz: "Milliy ko'rpa (kelin uchun)",
    title_ru: 'Национальное одеяло (для невесты)',
    title_en: 'Traditional Bridal Quilt',
    description_uz: "Qo'lda tikilgan, milliy naqshli, kelin sovg'asi uchun ideal",
    description_ru: 'Ручной работы, с национальным орнаментом, идеально для невесты',
    description_en: 'Handstitched with traditional patterns, ideal bridal gift',
    category: 'korpa_toshak',
    price_uzs: 850000,
    images: UNSPLASH.korpa_toshak,
    sizes_available: ['Single', 'Double', 'King'],
    is_custom_order: true,
    is_featured: true,
    in_stock: true,
    stock_count: 5,
  },
  {
    title_uz: "Bolalar ko'ylagi",
    title_ru: 'Детское платье',
    title_en: "Children's Dress",
    description_uz: "Ipak matolardan tikilgan, bolalar uchun qulay va chiroyli ko'ylak",
    description_ru: 'Сшито из шёлковых тканей, удобное и красивое детское платье',
    description_en: 'Silk fabric dress, comfortable and beautiful for children',
    category: 'tikuvchilik',
    price_uzs: 120000,
    images: UNSPLASH.tikuvchilik,
    sizes_available: ['2-3 yosh', '4-5 yosh', '6-7 yosh', '8-9 yosh'],
    is_custom_order: false,
    is_featured: true,
    in_stock: true,
    stock_count: 12,
  },
  {
    title_uz: "Choyshab to'plami",
    title_ru: 'Комплект постельного белья',
    title_en: 'Bedding Set',
    description_uz: "Yuqori sifatli mato, 4 qismli to'plam",
    description_ru: 'Высококачественная ткань, комплект из 4 предметов',
    description_en: 'High-quality fabric, 4-piece set',
    category: 'tikuvchilik',
    price_uzs: 450000,
    images: UNSPLASH.tikuvchilik,
    sizes_available: ['Single', 'Double'],
    is_custom_order: false,
    is_featured: false,
    in_stock: true,
    stock_count: 8,
  },
  {
    title_uz: "Qo'lda to'qilgan qo'g'irchoq (qiz)",
    title_ru: 'Вязаная кукла (девочка)',
    title_en: 'Handknit Doll (Girl)',
    description_uz: "Xavfsiz materiallardan to'qilgan, bolalar uchun",
    description_ru: 'Связано из безопасных материалов для детей',
    description_en: 'Knitted from safe materials for children',
    category: 'qogirchoq',
    price_uzs: 85000,
    images: UNSPLASH.qogirchoq,
    sizes_available: ['Kichik', "O'rta", 'Katta'],
    is_custom_order: true,
    is_featured: true,
    in_stock: true,
    stock_count: 20,
  },
  {
    title_uz: "Qo'lda to'qilgan hayvon o'yinchoq",
    title_ru: 'Вязаная игрушка-животное',
    title_en: 'Handknit Animal Toy',
    description_uz: "Turli hayvon shaklidagi qo'lda to'qilgan o'yinchoqlar",
    description_ru: 'Вязаные игрушки в виде различных животных',
    description_en: 'Various animal shaped handknit toys',
    category: 'qogirchoq',
    price_uzs: 65000,
    images: UNSPLASH.qogirchoq,
    sizes_available: ['Kichik', "O'rta"],
    is_custom_order: false,
    is_featured: false,
    in_stock: true,
    stock_count: 30,
  },
  {
    title_uz: 'Suniy gul dasta (qizil atirgul)',
    title_ru: 'Искусственный букет (красные розы)',
    title_en: 'Artificial Flower Bouquet (Red Roses)',
    description_uz: "Qo'lda yasalgan, uzoq vaqt saqlanadigan suniy gullar",
    description_ru: 'Ручная работа, долговечные искусственные цветы',
    description_en: 'Handmade, long-lasting artificial flowers',
    category: 'gulchilik',
    price_uzs: 180000,
    images: UNSPLASH.gulchilik,
    sizes_available: ['Kichik (5 ta)', "O'rta (11 ta)", 'Katta (21 ta)'],
    is_custom_order: true,
    is_featured: true,
    in_stock: true,
    stock_count: 15,
  },
  {
    title_uz: "Sovg'a gul quticha",
    title_ru: 'Подарочная коробка с цветами',
    title_en: 'Gift Flower Box',
    description_uz: "Sovg'a uchun maxsus bezatilgan gul quticha",
    description_ru: 'Специально украшенная коробка с цветами для подарка',
    description_en: 'Specially decorated flower box for gifting',
    category: 'gulchilik',
    price_uzs: 250000,
    images: UNSPLASH.gulchilik,
    sizes_available: ['Kichik', "O'rta", 'Katta'],
    is_custom_order: true,
    is_featured: false,
    in_stock: true,
    stock_count: 10,
  },
  {
    title_uz: 'Bolalar jinfirchasi',
    title_ru: 'Детский свитер',
    title_en: "Children's Sweater",
    description_uz: "Yumshoq ip bilan to'qilgan, issiq bolalar jinfirlari",
    description_ru: 'Связан из мягкой пряжи, тёплый детский свитер',
    description_en: 'Soft yarn knitted warm children sweater',
    category: 'toqivchilik',
    price_uzs: 95000,
    images: UNSPLASH.toqivchilik,
    sizes_available: ['2-3 yosh', '4-5 yosh', '6-8 yosh'],
    is_custom_order: false,
    is_featured: true,
    in_stock: true,
    stock_count: 18,
  },
  {
    title_uz: "Matras (o'rta razmer)",
    title_ru: 'Матрас (средний размер)',
    title_en: 'Mattress (Medium Size)',
    description_uz: "Qo'lda yasalgan, paxta to'ldirilgan, qulay matras",
    description_ru: 'Ручная работа, хлопковая набивка, удобный матрас',
    description_en: 'Handmade, cotton-filled, comfortable mattress',
    category: 'korpa_toshak',
    price_uzs: 650000,
    images: UNSPLASH.korpa_toshak,
    sizes_available: ['Single (90x190)', 'Double (140x190)', 'King (160x200)'],
    is_custom_order: false,
    is_featured: false,
    in_stock: true,
    stock_count: 6,
  },
  {
    title_uz: "To'liq ko'rpa-to'shak to'plami",
    title_ru: 'Полный комплект постельных принадлежностей',
    title_en: 'Complete Bedding Set',
    description_uz: "Ko'rpa, yostiq, choyshab va pardadan iborat to'liq to'plam",
    description_ru: 'Полный комплект: одеяло, подушка, простыня и наволочка',
    description_en: 'Complete set: quilt, pillow, sheet and pillowcase',
    category: 'korpa_toshak',
    price_uzs: 1200000,
    images: UNSPLASH.korpa_toshak,
    sizes_available: ['Single', 'Double', 'Family'],
    is_custom_order: true,
    is_featured: true,
    in_stock: true,
    stock_count: 3,
  },
  {
    title_uz: "Hidli sovun to'plami",
    title_ru: 'Набор ароматного мыла',
    title_en: 'Scented Soap Set',
    description_uz: "Qo'lda yasalgan tabiiy hidli sovunlar to'plami",
    description_ru: 'Набор натурального мыла ручной работы с ароматом',
    description_en: 'Handmade natural scented soap collection',
    category: 'qandolatchilik',
    price_uzs: 120000,
    images: UNSPLASH.qandolatchilik,
    sizes_available: ['3 ta', '6 ta', '12 ta'],
    is_custom_order: false,
    is_featured: false,
    in_stock: true,
    stock_count: 25,
  },
  {
    title_uz: 'Dekorativ milliy yostiq',
    title_ru: 'Декоративная национальная подушка',
    title_en: 'Decorative Traditional Pillow',
    description_uz: "Milliy naqshli, dekorativ maqsadda ishlatiladigan chiroyli yostiq",
    description_ru: 'Красивая декоративная подушка с национальным орнаментом',
    description_en: 'Beautiful decorative pillow with traditional patterns',
    category: 'korpa_toshak',
    price_uzs: 160000,
    images: UNSPLASH.korpa_toshak,
    sizes_available: ['30x30 sm', '40x40 sm', '50x50 sm'],
    is_custom_order: false,
    is_featured: false,
    in_stock: true,
    stock_count: 14,
  },
];

export async function runSeed(): Promise<void> {
  const { error } = await supabase.from('products').insert(seedProducts);
  if (error) throw error;
}
